f = open("writesample.txt","w")
f.write("hello im harsha\n")
f.write("Im learning Python\n")
f.write("hello im harsha\n")
f.write("Im learning Python")
f.close()

f = open("writesample.txt","a")
f.write("hello im harsha\n")
f.write("Im learning Python\n")
f.write("hello im harsha\n")
f.write("Im learning Python")
f.close()
